name: "Build"

on:
  push:
    tags: [ '*' ]
    branches: [ 'master' ]

  workflow_dispatch: {}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - id: context
        uses: milaboratory/github-ci/actions/context/init@v2
        with:
          version-canonize: false

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/java-gradle-app.yaml@v2
    with:
      # Environment
      java-version: '11'
      app-name: MiXCR
      app-name-slug: 'mixcr'

      # Distribution
      dist-archive-tasks: 'distributionZip'
      dist-archive-paths: './distributions/*.zip'

      # Release to S3
      release-to-s3: true
      release-s3-add-version: true
      release-s3-add-sha: ${{ fromJSON(needs.init.outputs.is-release) && 'false' || '8' }}

      # Send notifications
      notify-telegram: true

    secrets:
      GRADLE_PROPERTIES: |
        miRepoAccessKeyId=${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        miRepoSecretAccessKey= ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      AWS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_KEY_SECRET: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}

